# Generated by Django 3.2 on 2023-06-09 16:00

from django.db import migrations, models
import recipes.validation


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=255, unique=True, validators=[recipes.validation.validate_even], verbose_name='Название'),
        ),
    ]
