# Generated by Django 3.2 on 2023-06-10 16:12

from django.db import migrations, models
import recipes.validation


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=255, unique=True, validators=[recipes.validation.validate_mark], verbose_name='Название'),
        ),
    ]
